### ISSUE TITLE
installation instructions?

### ISSUE THREAD

**Issue by dougwyu** [clauswilke/dviz.supp#2]
Hi 
would you please provide installation instructions?  Thank you in advance

I tried this:

`library(devtools)
devtools::install_github("wilkelab/cowplot")
install.packages("colorspace", repos = "http://R-Forge.R-project.org")
devtools::install_github("clauswilke/colorblindr")
devtools::install_github("clauswilke/dviz.supp")
`

However, i got the following error message when trying to install dviz.supp

> ** byte-compile and prepare package for lazy loading
Note: possible error in 'ggdraw(p, clip = clip)': unused argument (clip = clip) 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘dviz.supp’:
 .onAttach failed in attachNamespace() for 'dviz.supp', details:
  call: NULL
  error: 'set_null_device' is not an exported object from 'namespace:cowplot'
Error: loading failed
Execution halted
ERROR: loading failed
\* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/dviz.supp’
Installation failed: Command failed (1)

I'm running on macOS 10.13, RStudio 1.1.453, and R 3.5.0

**Comment by clauswilke** [comment]
It doesn't look like you have the latest (development version) cowplot installed.

**Comment by clauswilke** [comment]
I have added remotes for cowplot and colorblindr. So as long as you have the correct colorspace library (1.4), everything else should now install automatically if you install this package with `devtools::install_github("clauswilke/dviz.supp")`.

**Comment by dougwyu** [comment]
Thanks.  

Fyi, macOS does not have dviz's preferred font, Myriad Pro, installed by default, so i was getting errors.  But it turns out that it's possible to get this font by installing Adobe Acrobat Reader DC, which is free.

[https://get.adobe.com/uk/reader/](url)

**Comment by dougwyu** [comment]
as i go through the markdown files, i discover the need to install some packages from github, not cran, especially ggforce.  Here is what i have so far 

library(devtools)
install.packages("colorspace", repos = "http://R-Forge.R-project.org") # 1.4-0
devtools::install_github("thomasp85/ggforce", force = TRUE)
devtools::install_github("thomasp85/patchwork")
devtools::install_github("clauswilke/dviz.supp")

**Comment by lgellis** [comment]
FYI when installing cowplot and colorspace first it works for me!

```
devtools::install_github("wilkelab/cowplot")
library(cowplot)

install.packages("colorspace")
library(colorspace)

devtools::install_github("clauswilke/dviz.supp")
library(dviz.supp)
```
